# Whether to send playerdata (platform, os, etc.) to backend servers
use-proxy-data: false

# Stored characters for lowered numbers from resource pack
# using the format [-0123456789]
hud:
  numbers: "-0123456789"
  # Char used for alignment in the actionbar
  align-char: " "
  # Char used as a gap between text and icons in the actionbar
  space-char: " "

# Platforms
platform:
  fabric: ""
  forge: ""
  default: ""

# Devices
device:
  switch: ""
  xbox: ""
  playstation: ""
  default: ""

# Status
status:
  afk:
    rp: ""
    default: ""
  voice:
    rp: ""
    default: ""
  no-voice:
    rp: ""
    default: ""

# Chat
chat-display:
  enabled: true
  time: 80
  prefix-rp: ""
  prefix-default: ""
  color: ""

# Thermometer placeholder
temperature:
  # Thermometer chars which will be chosen based on the temperature range
  chars: "......"
  # Placeholder character to use in place of a thermometer for bedrock players
  default: "|"
  # Bottom of the range to map thermometers to (Celsius)
  range-low: -20
  # Top of the range to map thermometers to (Celsius)
  range-high: 60
  celsius:
    rp: ""
    default: "°C"
  fahrenheit:
    rp: ""
    default: "°F"
