# Whether to send playerdata (platform, os, etc.) to backend servers
use-proxy-data: false

# Stored characters for lowered numbers from resource pack
# using the format [-0123456789]
hud-numbers: "-0123456789"

# Platforms
platform:
  fabric: ""
  forge: ""
  default: ""

# Devices
device:
  switch: ""
  xbox: ""
  playstation: ""
  default: ""

# Status
status:
  afk:
    rp: ""
    default: ""
  voice:
    rp: ""
    default: ""
  no-voice:
    rp: ""
    default: ""

# Chat
chat-display:
  enabled: true
  time: 80
  prefix-rp: ""
  prefix-default: ""
  color: ""

# Thermometer placeholder
# 'temp' value is less than or equal to value specified (celsius)
temperature:
  cold:
    temp: 0
    rp: ""
    default: ""
  average:
    temp: 40
    rp: ""
    default: ""
  hot:
    # No temp need here, all values greater than average temp
    rp: ""
    default: ""
  celsius:
    rp: ""
    default: "°C"
  fahrenheit:
    rp: ""
    default: "°F"
