# Whether to send playerdata (platform, os, etc.) to backend servers
use-proxy-data: false

# Platforms
platform:
  fabric: ""
  forge: ""
  default: ""

# Devices
device:
  switch: ""
  xbox: ""
  playstation: ""
  default: ""

# Status
status:
  afk:
    rp: ""
    default: ""
  voice:
    rp: ""
    default: ""
  no-voice:
    rp: ""
    default: ""

# Chat
chat-display:
  enabled: true
  time: 80
  prefix-rp: ""
  prefix-default: ""
  color: ""

# Thermometer
thermometer:
  cold:
    rp: ""
    default: ""
  average:
    rp: ""
    default: ""
  hot:
    rp: ""
    default: ""