name: @name@
version: @version@
api-version: 1.16
softdepend: [TAB, Essentials, PlasmoVoice, RealisticSeasons]
depend: [PlaceholderAPI, floodgate, LuckPerms]
main: xyz.novaserver.placeholders.paper.Main
author: Nova
commands:
  novaph:
    permission: placeholders.admin
    description: Admin command, gives access to reloading.
permissions:
  placeholders.admin:
    default: op
    description: Gives permission to reload command.